### ISSUE TITLE
Drop in image quality in full size image

### ISSUE THREAD

**Issue by robert-dog** [sachinchoolur/lightGallery#1238]
Hi

There seems to be a bug displaying full resolution images. The image is really soft on actual size or zoomed to 1:1, especially when the viewport is smaller than the image.  

The size (calculated by 3dtransform?) is off by one to two pixels and this causes a noticable drop in image quality.  Ie. the "actual size" image in Lightgallery in my example has dimensions of 2049.56 x 1366.05 pixels. The real size is 2048 x 1365 pixels.

This issue is present in 2.2., 2.3. and 2.4 beta. You can see it in your demo page as well. 

Tested in latest Chrome and Edge on Windows 10. 

![LG soft image](https://user-images.githubusercontent.com/97314996/148620796-04d31527-82a9-4273-82a4-b4e772c0ba8c.jpg)

You can see the softness in Windows Chrome in the attached image  - the last image is 1:1 the same image on a browser window. 

Any plans on fixing the issue?  This might not be a problem in blogs etc. but in professional photography or art pages, the quality is not good enough. 

Other than this issue Lightgallery is really amazing, you have done a great job.

**Comment by sachinchoolur** [comment]
Yes, it is a known issue. The quality of the images is slightly reduced on some browsers in certain scenarios. 

And you are right. CSS transform is causing the issue. CSS transform is only required for the zoom animation and can be removed once the animation is completed. 
I've already fixed the issue locally but need some more time to test it properly as I completely re-wrote the zoom module. 

The fix will be mostly available in the next version

**Comment by lucian-tanase** [comment]
Hi,

We have tried v.2.4.0 and there is still an issue with zoom plugin on iOS devices, images look blurry when zoom is applied, indeed because how iOS handles CSS transform, on Android everything works fine. Can the zoom mechanism be improved so images will look sharp on iOS devices too?

Here is a pen describing the issue, it has an older gallery version but the same thing happens in v.2.4.0 too: https://codepen.io/lucian-tls/pen/wvPWYJa

We are ready for purchasing a license to use the plugin but only if the zoom issue can be fixed.

Thank you for your amazing work!

**Comment by sachinchoolur** [comment]
Yes, the issue is happening majorly on IOS, and the fix is not included in version 2.4.0.
It is not noticeable in most of that cases. But definitely an issue for a few images like in your demo. 

You can expect the fix in 2.5.0 along with many other zoom module improvements.

**Comment by lucian-tanase** [comment]
Thank you for looking into it, do you have an estimated time frame for v.2.5.0?

**Comment by sachinchoolur** [comment]
Actively working on it - https://github.com/sachinchoolur/lightGallery/tree/lg-zoom
